/**
 * .env対話入力ウィザード
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { createInterface, question, password, textInput } from '../prompts';

/**
 * .env設定項目の定義
 */
interface EnvConfig {
  // Atlassian連携
  ATLASSIAN_URL?: string;
  ATLASSIAN_EMAIL?: string;
  ATLASSIAN_API_TOKEN?: string;

  // GitHub連携
  GITHUB_ORG?: string;
  GITHUB_TOKEN?: string;

  // Confluence設定
  CONFLUENCE_PRD_SPACE?: string;
  CONFLUENCE_QA_SPACE?: string;
  CONFLUENCE_RELEASE_SPACE?: string;

  // JIRA設定
  JIRA_PROJECT_KEYS?: string;
}

/**
 * .envファイルを対話的に作成
 * @param targetPath .envファイルのパス（省略時は '.env'）
 */
export async function createEnvInteractively(targetPath: string = '.env'): Promise<void> {
  console.log('');
  console.log('========================================');
  console.log(' .env Interactive Setup');
  console.log('========================================');
  console.log('');

  // パスを絶対パスに変換
  const absolutePath = await resolveEnvPath(targetPath);
  console.log(`設定ファイル: ${absolutePath}`);
  console.log('');

  // 既存ファイルの確認
  const fileExists = await checkFileExists(absolutePath);
  if (fileExists) {
    const rl = createInterface();
    const overwrite = await question(
      rl,
      '⚠️  既存の.envファイルが見つかりました。上書きしますか？ (y/N): '
    );
    rl.close();

    if (overwrite.toLowerCase() !== 'y') {
      console.log('中止しました。');
      return;
    }
    console.log('');
  }

  // 対話的に設定値を入力
  const config = await collectEnvConfig();

  // .envファイルに保存
  await saveEnvFile(absolutePath, config);

  console.log('');
  console.log('✅ .envファイルを作成しました:');
  console.log(`   ${absolutePath}`);
  console.log('');
}

/**
 * .envファイルのパスを解決
 */
async function resolveEnvPath(targetPath: string): Promise<string> {
  // ~/.michi/.env の場合
  if (targetPath.startsWith('~/.michi/')) {
    const homeDir = os.homedir();
    const michiDir = path.join(homeDir, '.michi');

    // ディレクトリが存在しない場合は作成
    await fs.mkdir(michiDir, { recursive: true });

    return path.join(michiDir, '.env');
  }

  // 相対パスの場合は絶対パスに変換
  if (!path.isAbsolute(targetPath)) {
    return path.resolve(process.cwd(), targetPath);
  }

  return targetPath;
}

/**
 * ファイルが存在するかチェック
 */
async function checkFileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

/**
 * 対話的に設定値を収集
 */
async function collectEnvConfig(): Promise<EnvConfig> {
  const rl = createInterface();
  const config: EnvConfig = {};

  console.log('=== Atlassian連携設定 ===');
  console.log('');

  // Atlassian URL
  config.ATLASSIAN_URL = await textInput(rl, 'Atlassian URL (空白でスキップ): ', {
    defaultValue: '',
    validator: (input) => !input || input.startsWith('https://'),
    errorMessage: 'URLは "https://" で始まる必要があります。',
  });

  if (config.ATLASSIAN_URL) {
    // Atlassian Email
    config.ATLASSIAN_EMAIL = await textInput(rl, 'Atlassian Email: ', {
      validator: (input) => input.includes('@'),
      errorMessage: '有効なメールアドレスを入力してください。',
    });

    // Atlassian API Token（パスワード非表示）
    rl.close(); // パスワード入力前にreadlineを閉じる
    config.ATLASSIAN_API_TOKEN = await password('Atlassian API Token: ');

    // 新しいreadlineインターフェースを作成
    const rl2 = createInterface();

    // Confluence Space設定
    console.log('');
    console.log('=== Confluence Space設定 ===');
    console.log('');
    config.CONFLUENCE_PRD_SPACE = await textInput(rl2, 'PRD Space Key (空白でスキップ): ', {
      defaultValue: '',
    });
    config.CONFLUENCE_QA_SPACE = await textInput(rl2, 'QA Space Key (空白でスキップ): ', {
      defaultValue: '',
    });
    config.CONFLUENCE_RELEASE_SPACE = await textInput(rl2, 'Release Space Key (空白でスキップ): ', {
      defaultValue: '',
    });

    // JIRA Project Keys
    console.log('');
    console.log('=== JIRA設定 ===');
    console.log('');
    config.JIRA_PROJECT_KEYS = await textInput(rl2, 'JIRA Project Keys (カンマ区切り、空白でスキップ): ', {
      defaultValue: '',
    });

    rl2.close();
  } else {
    rl.close();
  }

  // GitHub連携設定
  const rl3 = createInterface();
  console.log('');
  console.log('=== GitHub連携設定 ===');
  console.log('');

  config.GITHUB_ORG = await textInput(rl3, 'GitHub Organization (空白でスキップ): ', {
    defaultValue: '',
  });

  if (config.GITHUB_ORG) {
    rl3.close();
    // GitHub Token（パスワード非表示）
    config.GITHUB_TOKEN = await password('GitHub Personal Access Token: ');
  } else {
    rl3.close();
  }

  return config;
}

/**
 * .envファイルに保存
 */
async function saveEnvFile(filePath: string, config: EnvConfig): Promise<void> {
  const lines: string[] = [
    '# Michi Configuration',
    '# Generated by: michi config:init --env',
    '',
  ];

  // Atlassian連携
  if (config.ATLASSIAN_URL) {
    lines.push('# Atlassian Integration');
    lines.push(`ATLASSIAN_URL=${config.ATLASSIAN_URL}`);
    lines.push(`ATLASSIAN_EMAIL=${config.ATLASSIAN_EMAIL || ''}`);
    lines.push(`ATLASSIAN_API_TOKEN=${config.ATLASSIAN_API_TOKEN || ''}`);
    lines.push('');
  }

  // Confluence Space
  if (config.CONFLUENCE_PRD_SPACE || config.CONFLUENCE_QA_SPACE || config.CONFLUENCE_RELEASE_SPACE) {
    lines.push('# Confluence Spaces');
    if (config.CONFLUENCE_PRD_SPACE) {
      lines.push(`CONFLUENCE_PRD_SPACE=${config.CONFLUENCE_PRD_SPACE}`);
    }
    if (config.CONFLUENCE_QA_SPACE) {
      lines.push(`CONFLUENCE_QA_SPACE=${config.CONFLUENCE_QA_SPACE}`);
    }
    if (config.CONFLUENCE_RELEASE_SPACE) {
      lines.push(`CONFLUENCE_RELEASE_SPACE=${config.CONFLUENCE_RELEASE_SPACE}`);
    }
    lines.push('');
  }

  // JIRA設定
  if (config.JIRA_PROJECT_KEYS) {
    lines.push('# JIRA Configuration');
    lines.push(`JIRA_PROJECT_KEYS=${config.JIRA_PROJECT_KEYS}`);
    lines.push('');
  }

  // GitHub連携
  if (config.GITHUB_ORG) {
    lines.push('# GitHub Integration');
    lines.push(`GITHUB_ORG=${config.GITHUB_ORG}`);
    lines.push(`GITHUB_TOKEN=${config.GITHUB_TOKEN || ''}`);
    lines.push('');
  }

  const content = lines.join('\n');

  // 一時ファイルに書き込んでからrenameする（アトミックな書き込み）
  const tmpPath = `${filePath}.tmp`;
  await fs.writeFile(tmpPath, content, { mode: 0o600 }); // 0o600: 所有者のみ読み書き可能
  await fs.rename(tmpPath, filePath);
}
